#!/usr/bin/env node
// ============================================================
// sync-db.js — Sync data from Google Drive Desktop to Vercel
// ============================================================
// Usage: npm run sync-db
//
// This script:
// 1. Reads participants.json from LOCAL_DATA_DIR (Google Drive)
// 2. Updates src/data/participants.ts (bundled default data)
// 3. Copies photos to public/photos/
// 4. Git commit + push to GitHub
// 5. Vercel auto-deploys with updated data
// ============================================================

const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const PROJECT_ROOT = path.resolve(__dirname, "..");

// Load .env.local manually (Next.js does this automatically, but Node doesn't)
const envPath = path.join(PROJECT_ROOT, ".env.local");
if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, "utf-8");
  for (const line of envContent.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const match = trimmed.match(/^([^=]+)=(.*)$/);
    if (match) {
      const key = match[1].trim();
      const val = match[2].trim().replace(/^["']|["']$/g, "");
      if (!process.env[key]) process.env[key] = val;
    }
  }
}

const LOCAL_DATA_DIR = process.env.LOCAL_DATA_DIR || "";

console.log("========================================");
console.log("  Sync DB — Google Drive → Vercel");
console.log("========================================\n");

if (!LOCAL_DATA_DIR) {
  console.error("❌ LOCAL_DATA_DIR not set!");
  console.error("   Set in .env.local:");
  console.error("   LOCAL_DATA_DIR=G:\\My Drive\\2026_Project_1\\db_se206\n");
  process.exit(1);
}

if (!fs.existsSync(LOCAL_DATA_DIR)) {
  console.error(`❌ Directory not found: ${LOCAL_DATA_DIR}\n`);
  process.exit(1);
}

// Step 1: Read participants.json from Google Drive
const jsonPath = path.join(LOCAL_DATA_DIR, "participants.json");
if (!fs.existsSync(jsonPath)) {
  console.error(`❌ participants.json not found at: ${jsonPath}\n`);
  process.exit(1);
}

console.log(`📁 Reading: ${jsonPath}`);
const participants = JSON.parse(fs.readFileSync(jsonPath, "utf-8"));
console.log(`✅ Found ${participants.length} participants\n`);

// Step 2: Update src/data/participants.ts
const tsContent = `// Participant data for Pelatihan Petugas SE2026
// BPS Kabupaten Tasikmalaya
// Auto-generated by sync-db.js — DO NOT EDIT MANUALLY
// Last updated: ${new Date().toLocaleString("id-ID", { timeZone: "Asia/Jakarta" })}

export interface Participant {
  sobat_id: string;
  nama: string;
  kecamatan: string;
  gelombang: string;
  tempat_pelatihan: string;
  kelas: string;
  photo_filename: string;
}

export const participants: Participant[] = ${JSON.stringify(participants, null, 2)};
`;

const tsPath = path.join(PROJECT_ROOT, "src", "data", "participants.ts");
fs.writeFileSync(tsPath, tsContent, "utf-8");
console.log(`📝 Updated: src/data/participants.ts\n`);

// Step 2b: Update public/data/participants.json (for Vercel read-only mode)
const publicDataDir = path.join(PROJECT_ROOT, "public", "data");
if (!fs.existsSync(publicDataDir)) {
  fs.mkdirSync(publicDataDir, { recursive: true });
}
const publicJsonPath = path.join(publicDataDir, "participants.json");
fs.writeFileSync(publicJsonPath, JSON.stringify(participants, null, 2), "utf-8");
console.log(`📝 Updated: public/data/participants.json (${participants.length} peserta)\n`);

// Step 3: Copy photos
const sourcePhotosDir = path.join(LOCAL_DATA_DIR, "photos");
const targetPhotosDir = path.join(PROJECT_ROOT, "public", "photos");

if (!fs.existsSync(targetPhotosDir)) {
  fs.mkdirSync(targetPhotosDir, { recursive: true });
}

if (fs.existsSync(sourcePhotosDir)) {
  // Get list of photos referenced by participants
  const referencedPhotos = new Set(
    participants
      .filter((p) => p.photo_filename)
      .map((p) => p.photo_filename)
  );

  // Build set of sobat_ids that have photos (base names without extension)
  const referencedBaseNames = new Set(
    participants
      .filter((p) => p.photo_filename)
      .map((p) => p.photo_filename.replace(/\.[^.]+$/, ""))
  );

  const sourceFiles = fs.readdirSync(sourcePhotosDir).filter((f) => {
    const ext = f.toLowerCase().split(".").pop();
    return ["jpg", "jpeg", "png", "gif", "webp"].includes(ext);
  });

  // Clean old photos from public/photos/ (keep logos)
  const logoFiles = new Set(["logo-bps.png", "logo-se.png", "logo-sensus-ekonomi.png"]);
  const existingFiles = fs.readdirSync(targetPhotosDir);
  let removedCount = 0;
  for (const f of existingFiles) {
    if (logoFiles.has(f)) continue;
    // Remove if: not referenced by any participant, OR same sobat_id but different extension
    const baseName = f.replace(/\.[^.]+$/, "");
    if (!referencedPhotos.has(f)) {
      // Not the current photo for this participant — delete it
      fs.unlinkSync(path.join(targetPhotosDir, f));
      removedCount++;
    }
  }
  if (removedCount > 0) console.log(`🗑️  Removed ${removedCount} old/unused photo(s) from public/photos/`);

  // Also clean old photos from Google Drive (same sobat_id, different extension)
  let gdriveRemoved = 0;
  for (const file of sourceFiles) {
    const baseName = file.replace(/\.[^.]+$/, "");
    if (referencedBaseNames.has(baseName) && !referencedPhotos.has(file)) {
      // This file has same sobat_id but is NOT the current photo — delete it
      fs.unlinkSync(path.join(sourcePhotosDir, file));
      gdriveRemoved++;
    }
  }
  if (gdriveRemoved > 0) console.log(`🗑️  Removed ${gdriveRemoved} old photo(s) from Google Drive`);

  // Copy new/updated photos
  let copiedCount = 0;
  for (const file of sourceFiles) {
    if (referencedPhotos.has(file)) {
      const src = path.join(sourcePhotosDir, file);
      const dst = path.join(targetPhotosDir, file);
      fs.copyFileSync(src, dst);
      copiedCount++;
    }
  }
  console.log(`📸 Copied ${copiedCount} photo(s) to public/photos/\n`);
} else {
  console.log("⚠️  No photos directory found in LOCAL_DATA_DIR\n");
}

// Step 4: Git commit and push
console.log("🔄 Pushing to GitHub...");
try {
  execSync("git add -A", { cwd: PROJECT_ROOT, stdio: "pipe" });

  const status = execSync("git status --porcelain", {
    cwd: PROJECT_ROOT,
    encoding: "utf-8",
  }).trim();

  if (!status) {
    console.log("✅ No changes to sync. Data is already up to date.\n");
  } else {
    const fileCount = status.split("\n").length;
    execSync(
      `git commit -m "Sync DB: ${participants.length} participants (${new Date().toLocaleDateString("id-ID")})"`,
      { cwd: PROJECT_ROOT, stdio: "pipe" }
    );
    execSync("git push origin main", { cwd: PROJECT_ROOT, stdio: "pipe" });
    console.log(`✅ Pushed ${fileCount} file(s) to GitHub\n`);
    console.log("🚀 Vercel will auto-deploy with updated data!\n");
  }
} catch (err) {
  console.error("❌ Git push failed:", err.message);
  console.error("   Try manually: git add -A && git commit -m 'sync' && git push\n");
}

console.log("========================================");
console.log("  Sync complete!");
console.log("========================================");
